### ISSUE TITLE
Conflict with @types/prompts

### ISSUE THREAD

**Issue by eaviles** [lifion/lifion-verify-deps#173]
The latest published version of @types/prompts is 2.0.9 but, if you get the list of versions available you get 2.4.0

```sh
❯ npm view @types/prompts versions
[
  '1.1.0', '1.1.1',
  '1.2.0', '2.0.0',
  '2.0.1', '2.0.2',
  '2.0.3', '2.0.4',
  '2.0.5', '2.0.6',
  '2.0.7', '2.0.8',
  '2.0.9', '2.4.0'
]
```

lifion-verify-deps is wrongly recommending installing version 2.4.0 as the latest is a different one:

```sh
❯ npm view @types/prompts@latest version
2.0.9
```

**Comment by jennyEckstein** [comment]
I am not able to reproduce this issue. 
1. Installed @types/prompts using `npm install --save @types/prompts // installs 2.0.9`
2. Manually upgraded to v2.4.0, run lifion-verify-deps, getting a recommendation to upgrade --> `@types/prompts is outdated: 2.4.0 → 2.0.9`
3. Manually set to v2.0.8, run lifion-verify-deps, getting a recommendation to upgrade --> `@types/prompts is outdated: 2.0.8 → 2.0.9`

Lastly, [here](https://github.com/lifion/lifion-verify-deps/blob/develop/lib/index.js#L59), we have a condition that will always pick latest version over highest available from the list, if the latest is smaller.

**Comment by jennyEckstein** [comment]
No work needed
